# Boost BT signal strength
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# Don't clear bonds on start
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n
# Make sure sleep is enabled/configured
CONFIG_ZMK_SLEEP=y
# ms before idle (default is 30000)
CONFIG_ZMK_IDLE_TIMEOUT=60000
# ms before deep sleep (15 min)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
